// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvmN4kLgWlhh57-J-7L4VEpqmQS1RM24',
    appId: '1:659925968161:web:9ecba1b3ec1a2e05d8ca60',
    messagingSenderId: '659925968161',
    projectId: 'petution-app',
    authDomain: 'petution-app.firebaseapp.com',
    storageBucket: 'petution-app.firebasestorage.app',
    measurementId: 'G-CLV8FFHG8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXX6H6v0lorEtK94YcT0ru8_kZpXbtWG4',
    appId: '1:659925968161:android:057e884f85737538d8ca60',
    messagingSenderId: '659925968161',
    projectId: 'petution-app',
    storageBucket: 'petution-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5BYgdyxMZsaJZ2atgzi5V-2qN4uR_sJY',
    appId: '1:659925968161:ios:dcee58b8d789c6c5d8ca60',
    messagingSenderId: '659925968161',
    projectId: 'petution-app',
    storageBucket: 'petution-app.firebasestorage.app',
    iosClientId: '659925968161-beoemrh2e9003q4p8obtnr4ma1vs6816.apps.googleusercontent.com',
    iosBundleId: 'com.example.petutionMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5BYgdyxMZsaJZ2atgzi5V-2qN4uR_sJY',
    appId: '1:659925968161:ios:dcee58b8d789c6c5d8ca60',
    messagingSenderId: '659925968161',
    projectId: 'petution-app',
    storageBucket: 'petution-app.firebasestorage.app',
    iosClientId: '659925968161-beoemrh2e9003q4p8obtnr4ma1vs6816.apps.googleusercontent.com',
    iosBundleId: 'com.example.petutionMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLvmN4kLgWlhh57-J-7L4VEpqmQS1RM24',
    appId: '1:659925968161:web:fe5dc9537ec4d56dd8ca60',
    messagingSenderId: '659925968161',
    projectId: 'petution-app',
    authDomain: 'petution-app.firebaseapp.com',
    storageBucket: 'petution-app.firebasestorage.app',
    measurementId: 'G-29DF1P8SYB',
  );
}
